name: graphes
on: [push]
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Installation
- name: upload du resultat
uses: actions/upload-artifact@v4
with:
name: (donner un nom arbitraire)
path: ~/graphes/g1.svg
run: sudo apt-get install -y graphviz plantuml
- name: Check out repository code
uses: actions/checkout@v3
- name: Lancement graphviz
run: graphviz1.sh g1
